### PR TITLE
The truth

### PR DESCRIPTION
**Pull request by cegredev**
It is the truth

### CODE REVIEW

**Comment by AgentJo** [comment]
noob

**Comment by cegredev** [comment]
nooOOOOOOOOOOOOO

**Comment by cegredev** [comment]
THIS IS RIGHT WING PROPAGANDA

**Comment by cegredev** [comment]
HE'S STOPPING FREE SPEECH

**Comment by cegredev** [comment]
LET THE REVOUTION BEGIN

**Comment by cegredev** [comment]
HAIL HYDRA

**Pull request closed without merging**
